version: '3.8'

services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  wiremock:
    image: wiremock/wiremock
    volumes:
      - ./wiremock:/home/wiremock
    command: --async-response-enabled=true --port 9999
    ports:
      - "9999:9998"

  toxiproxy:
    image: ghcr.io/shopify/toxiproxy
    ports:
      - "8474:8474" # toxiproxy API
      - "55432:55432" # toxiproxy PG
      - "9991:9991"
